name: ci_python

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install flake8 mypy
    - run: flake8
    - run: mypy .
